### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by RandomUsername12222** [Monsters-RPG-game/Gateway#134]
### Feature type

New Feature

### Description

# Monsters gateway roadmap

## Features for `1.0`:
- [X] Login system
- [X] Validating other services
- [x] Router
- [ ] Websocket
- [X] Caching
- [X] Migrations
- [X] Docs

### Login system
- [X] Initialize OIDC
- [X] Add migration creating basic keys
- [X] Add migration creating basic client
- [X] Connect redis adapter for data sharing

### Validating other services
- [X] Add heartbeat handler for other services
- [X] Ignore requests for dead services
- [ ] Send emails to admins that service died

### Router
- [X] Health
- [X] Routes for each service
- [x] Proper security as middleware ( helm etc )
- [X] Token validation
- [X] Profile initialization as cache

### Websocket
- [ ] Send notifications about messages
- [ ] Send other notifications
- [ ] Handle user login/logout
- [ ] Handle multi login
- [ ] Live chat
- [ ] Token validation

### Caching
- [X] Cache user profile in redis
- [X] Update cache on change

### Docs
- [X] Add swagger for routes
